### ISSUE TITLE
t/model_tests.t fails (with older YAML?)

### ISSUE THREAD

**Issue by eserte** [dod38fr/config-model#22]
I see this failure on a couple of my smokers:
```
Backend error: YAML Error: Stream does not end with newline character
   Code: YAML_PARSE_ERR_NO_FINAL_NEWLINE
   Line: 0
   Document: 0
 at /opt/perl-5.18.1d/lib/site_perl/5.18.1/YAML/Loader.pm line 38.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 106.
t/model_tests.t ................... 
Dubious, test returned 2 (wstat 512, 0x200)
All 106 subtests passed 
```
Looks like it fails with older YAML.pm (?), so maybe the prereq version should be increased.

**Comment by dod38fr** [comment]
This looks like it's triggered by an invalid YAML file users for tests:
```
$ yamllint t/model_tests.d/backend-yaml-data-examples/basic 
t/model_tests.d/backend-yaml-data-examples/basic
  5:14      error    no new line character at the end of file  (new-line-at-end-of-file)
```

Although I don't know why some versions of YAML accept this file ...

**Comment by dod38fr** [comment]
Fixed in v2.128. Thanks for the report

**Comment by eserte** [comment]
I still see test failures on a few of my smokers:
```
Configuration item 'record:yada' (class Host) has a Load data structure (perl) error:
	load_data called with non hash ref arg
$wrong data = '';
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 117.
t/model_tests.t ................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
```
Statistical analysis suggests that this happens with older YAML.pm (1.21 is OK, 1.17 is not):
```
****************************************************************
Regression 'mod:YAML'
****************************************************************
Name           	       Theta	      StdErr	 T-stat
[0='const']    	      0.0000	      0.0000	   0.45
[1='eq_1.17']  	      0.0000	      0.0000	   2.84
[2='eq_1.21']  	      1.0000	      0.0000	3042219659444398.50
[3='eq_1.23']  	      1.0000	      0.0000	6363258952483092.00
[4='eq_1.24']  	      1.0000	      0.0000	5426605468102586.00
[5='eq_1.26']  	      1.0000	      0.0000	7420771369274522.00
[6='eq_1.27']  	      1.0000	      0.0000	7451885851102386.00

R^2= 1.000, N= 95, K= 7
****************************************************************
```

**Comment by dod38fr** [comment]
Right.. YAML module is in a bad shape. YAML::XS is much  better now.

I can fix this issue by replacing YAML with a recent YAML::XS, but then Config::Model will require an XS dependency for an optional feature. So I'm going to spin off the YAML backend into a new module.

**Comment by dod38fr** [comment]
Done: Yaml backend is now based on YAML::XS and provided by [Config::Model::Backend::Yaml](https://metacpan.org/release/Config-Model-Backend-Yaml)
